### ISSUE TITLE
Android10崩溃NullPointerException

### ISSUE THREAD

**Issue by guangmingxiong9999** [opensource-zhuzhiqiang/smart-show#38]
java.lang.NullPointerException
Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
com.coder.zzq.smartshow.toast.s.a(VirtualToastManager.java:15)

**Comment by the-pig-of-jungle** [comment]
你好使用的是那个版本？

**Comment by the-pig-of-jungle** [comment]
你好，最新版已修复该bug
